name: Ubuntu VNC

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Getting Updates and Installing Tailscale, Git.
        run: |
          sudo apt update -y
          sudo apt install git wget -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Run
        run: |
             sudo apt update -y
             sudo apt install 
             sudo apt install websockify novnc tightvncserver -y
             mkdir ~/.vnc
             wget -O ~/.vnc/xstartup https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/startup
             chmod +x /home/runner/.vnc/xstartup
             chmod 666 /home/runner/.vnc/xstartup
             wget -O loop.sh https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/loop.sh
             sh loop.sh
